linters-settings:
  gci:
    # put imports beginning with prefix after 3rd-party packages;
    # only support one prefix
    # if not set, use goimports.local-prefixes
    local-prefixes: github.com/tjm/puppet-patching-automation
  goimports:
    local-prefixes: github.com/tjm/puppet-patching-automation
